import { MediaAsset, SubtitleSegment } from '@/types/timeline';

// High-quality, reliable sample assets with built-in fallback data URLs for instant offline preview
export const SAMPLE_ASSETS: MediaAsset[] = [
  {
    id: 'VID_01',
    type: 'video',
    name: 'Cyberpunk_City_Lights.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration: 15.0,
    width: 1080,
    height: 1920,
    thumbnailUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=600&auto=format&fit=crop&q=80',
    fileSize: 14500000,
  },
  {
    id: 'VID_02',
    type: 'video',
    name: 'Drone_Aerial_Metropolis.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration: 15.0,
    width: 1080,
    height: 1920,
    thumbnailUrl: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?w=600&auto=format&fit=crop&q=80',
    fileSize: 16200000,
  },
  {
    id: 'VID_03',
    type: 'video',
    name: 'Creator_Studio_Workflow.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration: 20.0,
    width: 1080,
    height: 1920,
    thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    fileSize: 18400000,
  },
  {
    id: 'VID_04',
    type: 'video',
    name: 'High_Speed_Neon_Motion.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    duration: 25.0,
    width: 1080,
    height: 1920,
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    fileSize: 22100000,
  },
  {
    id: 'IMG_01',
    type: 'image',
    name: 'AI_Neural_Interface.png',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1080&auto=format&fit=crop&q=80',
    duration: 5.0,
    width: 1080,
    height: 1920,
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    fileSize: 2800000,
  },
  {
    id: 'IMG_02',
    type: 'image',
    name: 'Minimal_Creative_Workspace.jpg',
    url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1080&auto=format&fit=crop&q=80',
    duration: 5.0,
    width: 1080,
    height: 1920,
    thumbnailUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80',
    fileSize: 3100000,
  },
  {
    id: 'IMG_03',
    type: 'image',
    name: 'Product_Launch_Banner.png',
    url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1080&auto=format&fit=crop&q=80',
    duration: 5.0,
    width: 1080,
    height: 1920,
    thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    fileSize: 2400000,
  },
  {
    id: 'VO_TRACK',
    type: 'voiceover',
    name: 'AutoCut_Official_Narration_60s.mp3',
    url: 'https://actions.google.com/sounds/v1/speech/commercial_female_intro.ogg',
    duration: 60.0,
    thumbnailUrl: '',
    fileSize: 1200000,
  },
  {
    id: 'BG_MUSIC',
    type: 'music',
    name: 'Cyberwave_Electronic_Groove.mp3',
    url: 'https://actions.google.com/sounds/v1/science_fiction/ambient_loop.ogg',
    duration: 60.0,
    thumbnailUrl: '',
    fileSize: 3800000,
  },
];

// Rich word-level synced timestamps for the 60-second voiceover track
export const SAMPLE_SUBTITLES: SubtitleSegment[] = [
  {
    id: 'sub_1',
    text: 'Welcome to AutoCut Studio. Ready to transform your editing?',
    startTime: 0.5,
    endTime: 4.8,
    words: [
      { word: 'Welcome', start: 0.5, end: 1.1 },
      { word: 'to', start: 1.1, end: 1.4 },
      { word: 'AutoCut', start: 1.4, end: 2.2 },
      { word: 'Studio.', start: 2.2, end: 2.9 },
      { word: 'Ready', start: 3.1, end: 3.6 },
      { word: 'to', start: 3.6, end: 3.9 },
      { word: 'transform', start: 3.9, end: 4.5 },
      { word: 'editing?', start: 4.5, end: 4.8 },
    ],
    style: 'viral-highlight',
  },
  {
    id: 'sub_2',
    text: 'Raw footage transforms into pure viral magic instantly.',
    startTime: 6.5,
    endTime: 10.8,
    words: [
      { word: 'Raw', start: 6.5, end: 7.0 },
      { word: 'footage', start: 7.0, end: 7.6 },
      { word: 'transforms', start: 7.6, end: 8.4 },
      { word: 'into', start: 8.4, end: 8.8 },
      { word: 'pure', start: 8.8, end: 9.3 },
      { word: 'viral', start: 9.3, end: 9.9 },
      { word: 'magic', start: 9.9, end: 10.4 },
      { word: 'instantly.', start: 10.4, end: 10.8 },
    ],
    style: 'viral-highlight',
  },
  {
    id: 'sub_3',
    text: 'Zero manual timeline editing. AI handles the sequencing.',
    startTime: 12.0,
    endTime: 16.5,
    words: [
      { word: 'Zero', start: 12.0, end: 12.6 },
      { word: 'manual', start: 12.6, end: 13.2 },
      { word: 'timeline', start: 13.2, end: 13.9 },
      { word: 'editing.', start: 13.9, end: 14.6 },
      { word: 'AI', start: 14.8, end: 15.2 },
      { word: 'handles', start: 15.2, end: 15.8 },
      { word: 'sequencing.', start: 15.8, end: 16.5 },
    ],
    style: 'viral-highlight',
  },
  {
    id: 'sub_4',
    text: 'Notice how background music ducks by sixteen decibels.',
    startTime: 18.0,
    endTime: 23.2,
    words: [
      { word: 'Notice', start: 18.0, end: 18.6 },
      { word: 'how', start: 18.6, end: 18.9 },
      { word: 'background', start: 18.9, end: 19.6 },
      { word: 'music', start: 19.6, end: 20.2 },
      { word: 'ducks', start: 20.2, end: 20.8 },
      { word: 'by', start: 20.8, end: 21.2 },
      { word: 'sixteen', start: 21.2, end: 22.0 },
      { word: 'decibels.', start: 22.0, end: 23.2 },
    ],
    style: 'viral-highlight',
  },
  {
    id: 'sub_5',
    text: 'Dynamic transitions snap. Whip pans, zoom snaps, and glitch.',
    startTime: 25.0,
    endTime: 30.5,
    words: [
      { word: 'Dynamic', start: 25.0, end: 25.7 },
      { word: 'transitions', start: 25.7, end: 26.5 },
      { word: 'snap.', start: 26.5, end: 27.2 },
      { word: 'Whip', start: 27.5, end: 28.0 },
      { word: 'pans,', start: 28.0, end: 28.6 },
      { word: 'zoom', start: 28.6, end: 29.2 },
      { word: 'snaps,', start: 29.2, end: 29.8 },
      { word: 'and', start: 29.8, end: 30.0 },
      { word: 'glitch.', start: 30.0, end: 30.5 },
    ],
    style: 'viral-highlight',
  },
  {
    id: 'sub_6',
    text: 'Static photos come alive with Ken Burns motion and glow.',
    startTime: 32.5,
    endTime: 37.8,
    words: [
      { word: 'Static', start: 32.5, end: 33.1 },
      { word: 'photos', start: 33.1, end: 33.7 },
      { word: 'come', start: 33.7, end: 34.2 },
      { word: 'alive', start: 34.2, end: 34.8 },
      { word: 'with', start: 34.8, end: 35.2 },
      { word: 'Ken', start: 35.2, end: 35.6 },
      { word: 'Burns', start: 35.6, end: 36.2 },
      { word: 'motion', start: 36.2, end: 36.8 },
      { word: 'and', start: 36.8, end: 37.1 },
      { word: 'glow.', start: 37.1, end: 37.8 },
    ],
    style: 'viral-highlight',
  },
  {
    id: 'sub_7',
    text: 'AutoCut Studio delivers 1080 by 1920 ready to dominate.',
    startTime: 40.0,
    endTime: 45.2,
    words: [
      { word: 'AutoCut', start: 40.0, end: 40.7 },
      { word: 'Studio', start: 40.7, end: 41.3 },
      { word: 'delivers', start: 41.3, end: 41.9 },
      { word: 'ten-eighty', start: 41.9, end: 42.7 },
      { word: 'by', start: 42.7, end: 43.1 },
      { word: 'nineteen-twenty', start: 43.1, end: 44.0 },
      { word: 'ready', start: 44.0, end: 44.5 },
      { word: 'to', start: 44.5, end: 44.7 },
      { word: 'dominate.', start: 44.7, end: 45.2 },
    ],
    style: 'viral-highlight',
  },
  {
    id: 'sub_8',
    text: 'Scale your content 100x. No keyframes. Pure automated speed.',
    startTime: 48.0,
    endTime: 54.0,
    words: [
      { word: 'Scale', start: 48.0, end: 48.6 },
      { word: 'your', start: 48.6, end: 48.9 },
      { word: 'content', start: 48.9, end: 49.6 },
      { word: 'hundred-x.', start: 49.6, end: 50.6 },
      { word: 'No', start: 51.0, end: 51.4 },
      { word: 'keyframes.', start: 51.4, end: 52.2 },
      { word: 'Pure', start: 52.4, end: 52.9 },
      { word: 'speed.', start: 52.9, end: 54.0 },
    ],
    style: 'viral-highlight',
  },
  {
    id: 'sub_9',
    text: 'AutoCut Studio. Your AI Video Director is here.',
    startTime: 55.5,
    endTime: 59.5,
    words: [
      { word: 'AutoCut', start: 55.5, end: 56.2 },
      { word: 'Studio.', start: 56.2, end: 57.0 },
      { word: 'Your', start: 57.2, end: 57.6 },
      { word: 'AI', start: 57.6, end: 58.0 },
      { word: 'Director', start: 58.0, end: 58.7 },
      { word: 'is', start: 58.7, end: 59.0 },
      { word: 'here.', start: 59.0, end: 59.5 },
    ],
    style: 'viral-highlight',
  },
];

// Pre-built default 60-second timeline configuration
export const DEFAULT_TIMELINE = {
  title: 'AutoCut Studio Demo 60s Reel',
  totalDuration: 60,
  fps: 30,
  aspectRatio: '9:16' as const,
  width: 1080,
  height: 1920,
  clips: [
    {
      id: 'clip_1',
      assetId: 'VID_01',
      startTime: 0,
      duration: 6.5,
      sourceStart: 0,
      transition: 'none' as const,
      motionEffect: 'none' as const,
      colorFilter: 'cyber' as const,
      volume: 0,
    },
    {
      id: 'clip_2',
      assetId: 'IMG_01',
      startTime: 6.5,
      duration: 5.5,
      sourceStart: 0,
      transition: 'whip-pan' as const,
      motionEffect: 'ken-burns-zoom-in' as const,
      colorFilter: 'high-contrast' as const,
      volume: 0,
    },
    {
      id: 'clip_3',
      assetId: 'VID_02',
      startTime: 12.0,
      duration: 8.0,
      sourceStart: 1.0,
      transition: 'zoom-snap' as const,
      motionEffect: 'none' as const,
      colorFilter: 'teal-orange' as const,
      volume: 0,
    },
    {
      id: 'clip_4',
      assetId: 'IMG_02',
      startTime: 20.0,
      duration: 5.0,
      sourceStart: 0,
      transition: 'cross-dissolve' as const,
      motionEffect: 'pan-left' as const,
      colorFilter: 'warm-vintage' as const,
      volume: 0,
    },
    {
      id: 'clip_5',
      assetId: 'VID_03',
      startTime: 25.0,
      duration: 7.5,
      sourceStart: 0.5,
      transition: 'glitch' as const,
      motionEffect: 'none' as const,
      colorFilter: 'cinematic' as const,
      volume: 0,
    },
    {
      id: 'clip_6',
      assetId: 'IMG_03',
      startTime: 32.5,
      duration: 6.0,
      sourceStart: 0,
      transition: 'zoom-snap' as const,
      motionEffect: 'pulse' as const,
      colorFilter: 'high-contrast' as const,
      volume: 0,
    },
    {
      id: 'clip_7',
      assetId: 'VID_04',
      startTime: 38.5,
      duration: 8.5,
      sourceStart: 2.0,
      transition: 'whip-pan' as const,
      motionEffect: 'none' as const,
      colorFilter: 'cyber' as const,
      volume: 0,
    },
    {
      id: 'clip_8',
      assetId: 'VID_01',
      startTime: 47.0,
      duration: 7.0,
      sourceStart: 6.0,
      transition: 'glitch' as const,
      motionEffect: 'none' as const,
      colorFilter: 'noir' as const,
      volume: 0,
    },
    {
      id: 'clip_9',
      assetId: 'VID_02',
      startTime: 54.0,
      duration: 6.0,
      sourceStart: 8.0,
      transition: 'cross-dissolve' as const,
      motionEffect: 'none' as const,
      colorFilter: 'teal-orange' as const,
      volume: 0,
    },
  ],
  voiceover: {
    assetId: 'VO_TRACK',
    volume: 1.0,
    ducking: true,
    duckingAttenuationDb: -16,
    fadeInDuration: 0.2,
    fadeOutDuration: 0.5,
  },
  backgroundMusic: {
    assetId: 'BG_MUSIC',
    volume: 0.35,
    ducking: false,
    duckingAttenuationDb: -16,
    fadeInDuration: 0.5,
    fadeOutDuration: 1.0,
  },
  subtitles: SAMPLE_SUBTITLES,
  pacing: 'viral-fast' as const,
  directorNotes: 'High-energy 60-second vertical cut optimized for TikTok/Reels retention. Starts with intense cyber visual hook, snaps to dynamic Ken Burns zooms on UI banners, rhythmic whip pans, auto-ducked music during high-impact narration, and punchy Alex Hormozi style captions.',
};
